GET http://localhost:5000
Content-Type: application/json

####
GET http://localhost:5000/login?username=peter&password=asdf
Content-Type: application/json

####
GET http://localhost:5000/user?username=peter&password=asdf
Content-Type: application/json
